export const TENANTS_REQUEST = 'TENANTS_REQUEST';
export const TENANTS_RECEIVE = 'TENANTS_RECEIVE';
export const TENANTS_FAILURE = 'TENANTS_FAILURE';

export const TENANT_DETAIL_REQUEST = 'TENANT_DETAIL_REQUEST';
export const TENANT_DETAIL_RECEIVE = 'TENANT_DETAIL_RECEIVE';
export const TENANT_DETAIL_FAILURE = 'TENANT_DETAIL_FAILURE';
export const TENANT_DETAIL_ERASE = 'TENANT_DETAIL_ERASE';

export const TENANTS_MORE_REQUEST = 'TENANTS_MORE_REQUEST';
export const TENANTS_MORE_RECEIVE = 'TENANTS_MORE_RECEIVE';

export const TENANTS_SET_FILTER = 'TENANTS_SET_FILTER';

export const TENANTS_SELECT = 'TENANTS_SELECT';
export const TENANTS_DESELECT = 'TENANTS_DESELECT';
export const TENANTS_SELECT_ALL = 'TENANTS_SELECT_ALL';
export const TENANTS_DESELECT_ALL = 'TENANTS_DESELECT_ALL';

export const TENANT_UPDATE_REQUEST = 'TENANT_UPDATE_REQUEST';
export const TENANT_UPDATE_SUCCESS = 'TENANT_UPDATE_SUCCESS';
export const TENANT_UPDATE_FAILURE = 'TENANT_UPDATE_FAILURE';
export const TENANT_DELETE_SUCCESS = 'TENANT_DELETE_SUCCESS';

export const TENANT_CREATE_REQUEST = 'TENANT_CREATE_REQUEST';
export const TENANT_CREATE_SUCCESS = 'TENANT_CREATE_SUCCESS';
export const TENANT_CREATE_FAILURE = 'TENANT_CREATE_FAILURE';
export const TENANT_CREATE_ERASE = 'TENANT_CREATE_ERASE';
