export const DISCOUNTS_REQUEST = 'DISCOUNTS_REQUEST';
export const DISCOUNTS_RECEIVE = 'DISCOUNTS_RECEIVE';
export const DISCOUNTS_FAILURE = 'DISCOUNTS_FAILURE';

export const DISCOUNT_DETAIL_REQUEST = 'DISCOUNT_DETAIL_REQUEST';
export const DISCOUNT_DETAIL_RECEIVE = 'DISCOUNT_DETAIL_RECEIVE';
export const DISCOUNT_DETAIL_FAILURE = 'DISCOUNT_DETAIL_FAILURE';
export const DISCOUNT_DETAIL_ERASE = 'DISCOUNT_DETAIL_ERASE';

export const DISCOUNTS_MORE_REQUEST = 'DISCOUNTS_MORE_REQUEST';
export const DISCOUNTS_MORE_RECEIVE = 'DISCOUNTS_MORE_RECEIVE';

export const DISCOUNTS_SET_FILTER = 'DISCOUNTS_SET_FILTER';

export const DISCOUNTS_SELECT = 'DISCOUNTS_SELECT';
export const DISCOUNTS_DESELECT = 'DISCOUNTS_DESELECT';
export const DISCOUNTS_SELECT_ALL = 'DISCOUNTS_SELECT_ALL';
export const DISCOUNTS_DESELECT_ALL = 'DISCOUNTS_DESELECT_ALL';

export const DISCOUNT_UPDATE_REQUEST = 'DISCOUNT_UPDATE_REQUEST';
export const DISCOUNT_UPDATE_SUCCESS = 'DISCOUNT_UPDATE_SUCCESS';
export const DISCOUNT_UPDATE_FAILURE = 'DISCOUNT_UPDATE_FAILURE';
export const DISCOUNT_DELETE_SUCCESS = 'DISCOUNT_DELETE_SUCCESS';

export const DISCOUNT_CREATE_REQUEST = 'DISCOUNT_CREATE_REQUEST';
export const DISCOUNT_CREATE_SUCCESS = 'DISCOUNT_CREATE_SUCCESS';
export const DISCOUNT_CREATE_FAILURE = 'DISCOUNT_CREATE_FAILURE';
export const DISCOUNT_CREATE_ERASE = 'DISCOUNT_CREATE_ERASE';
