export const PRODUCT_REQUEST = 'PRODUCT_REQUEST';
export const PRODUCT_RECEIVE = 'PRODUCT_RECEIVE';
//export const PRODUCT_FAILURE = 'PRODUCT_FAILURE'

export const PRODUCTS_REQUEST = 'PRODUCTS_REQUEST';
export const PRODUCTS_RECEIVE = 'PRODUCTS_RECEIVE';
// export const PRODUCTS_FAILURE = 'PRODUCTS_FAILURE'

export const MORE_PRODUCTS_REQUEST = 'MORE_PRODUCTS_REQUEST';
export const MORE_PRODUCTS_RECEIVE = 'MORE_PRODUCTS_RECEIVE';
// export const MORE_PRODUCTS_FAILURE = 'MORE_PRODUCTS_FAILURE'

export const PAGE_REQUEST = 'PAGE_REQUEST';
export const PAGE_RECEIVE = 'PAGE_RECEIVE';
// export const PAGE_FAILURE = 'PAGE_FAILURE'

export const CART_REQUEST = 'CART_REQUEST';
export const CART_RECEIVE = 'CART_RECEIVE';
// export const CART_FAILURE = 'CART_FAILURE'

export const CART_ITEM_ADD_REQUEST = 'CART_ITEM_ADD_REQUEST';
// export const CART_ITEM_ADD_RECEIVE = 'CART_ITEM_ADD_RECEIVE'
// export const CART_ITEM_ADD_FAILURE = 'CART_ITEM_ADD_FAILURE'

export const CART_ITEM_DELETE_REQUEST = 'CART_ITEM_DELETE_REQUEST';
// export const CART_ITEM_DELETE_RECEIVE = 'CART_ITEM_DELETE_RECEIVE'
// export const CART_ITEM_DELETE_FAILURE = 'CART_ITEM_DELETE_FAILURE'

export const CART_ITEM_UPDATE_REQUEST = 'CART_ITEM_UPDATE_REQUEST';
// export const CART_ITEM_UPDATE_RECEIVE = 'CART_ITEM_UPDATE_RECEIVE'
// export const CART_ITEM_UPDATE_FAILURE = 'CART_ITEM_UPDATE_FAILURE'

export const SHIPPING_METHODS_REQUEST = 'SHIPPING_METHODS_REQUEST';
export const SHIPPING_METHODS_RECEIVE = 'SHIPPING_METHODS_RECEIVE';
// export const SHIPPING_METHODS_FAILURE = 'SHIPPING_METHODS_FAILURE'

export const PAYMENT_METHODS_REQUEST = 'PAYMENT_METHODS_REQUEST';
export const PAYMENT_METHODS_RECEIVE = 'PAYMENT_METHODS_RECEIVE';
// export const PAYMENT_METHODS_FAILURE = 'PAYMENT_METHODS_FAILURE'

export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_RECEIVE = 'CHECKOUT_RECEIVE';
// export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'

export const SITEMAP_REQUEST = 'SITEMAP_REQUEST';
export const SITEMAP_RECEIVE = 'SITEMAP_RECEIVE';
// export const SITEMAP_FAILURE = 'SITEMAP_FAILURE'

export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY';
export const SET_PRODUCTS_FILTER = 'SET_PRODUCTS_FILTER';

export const LOCATION_CHANGED = 'LOCATION_CHANGED';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_RECEIVE = 'RESET_PASSWORD_RECEIVE';

export const ACTIVE_ACCOUNT_REQUEST = 'ACTIVE_ACCOUNT_REQUEST';
export const ACTIVE_ACCOUNT_RECEIVE = 'ACTIVE_ACCOUNT_RECEIVE';

export const USER_REQUEST = 'USER_REQUEST';
export const USER_RECEIVE = 'USER_RECEIVE';

export const DISCOUNT_REQUEST = 'DISCOUNT_REQUEST';
export const DISCOUNT_RECEIVE = 'DISCOUNT_RECEIVE';
export const DISCOUNT_APPLY_FAILURE = 'DISCOUNT_APPLY_FAILURE';
