export const USERS_REQUEST = 'USERS_REQUEST';
export const USERS_RECEIVE = 'USERS_RECEIVE';
export const USERS_FAILURE = 'USERS_FAILURE';

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST';
export const USER_DETAIL_RECEIVE = 'USER_DETAIL_RECEIVE';
export const USER_DETAIL_FAILURE = 'USER_DETAIL_FAILURE';
export const USER_DETAIL_ERASE = 'USER_DETAIL_ERASE';

export const USERS_MORE_REQUEST = 'USERS_MORE_REQUEST';
export const USERS_MORE_RECEIVE = 'USERS_MORE_RECEIVE';

export const USERS_SET_FILTER = 'USERS_SET_FILTER';

export const USERS_SELECT = 'USERS_SELECT';
export const USERS_DESELECT = 'USERS_DESELECT';
export const USERS_SELECT_ALL = 'USERS_SELECT_ALL';
export const USERS_DESELECT_ALL = 'USERS_DESELECT_ALL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';

export const USER_CREATE_REQUEST = 'USER_CREATE_REQUEST';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';
export const USER_CREATE_ERASE = 'USER_CREATE_ERASE';
